name: WebSocket Benchmark

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  benchmark:
    name: Run Benchmarks and Report
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v6

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: stable
        cache: true
        cache-dependency-path: 'go.sum'

    - name: Run the benchmarks
      uses: CodSpeedHQ/action@v4
      with:
        mode: walltime
        run: go test -bench=BenchmarkWSEcho
    
    - name: Run benchmarks with pprof
      run: |
        go test -bench=BenchmarkWSEcho -benchmem -cpuprofile=cpu.prof -memprofile=mem.prof

    - name: Analyze pprof
      run: |
        echo "### 🔬 CPU 性能分析 (Top 20 自身耗时 - Flat)" >> $GITHUB_STEP_SUMMARY
        echo '```text' >> $GITHUB_STEP_SUMMARY
        go tool pprof -top -nodecount=20 ./bench cpu.prof >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        echo "### 🔬 CPU 性能分析 (Top 20 累计耗时 - Cum)" >> $GITHUB_STEP_SUMMARY
        echo '```text' >> $GITHUB_STEP_SUMMARY
        go tool pprof -top -cum -nodecount=20 ./bench cpu.prof >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        # ---------------- 内存分析 ----------------
        echo "### 🧠 内存分配分析 (Top 20 自身分配 - Flat)" >> $GITHUB_STEP_SUMMARY
        echo '```text' >> $GITHUB_STEP_SUMMARY
        go tool pprof -top -nodecount=20 ./bench mem.prof >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        
        echo "### 🧠 内存分配分析 (Top 20 累计分配 - Cum)" >> $GITHUB_STEP_SUMMARY
        echo '```text' >> $GITHUB_STEP_SUMMARY
        go tool pprof -top -cum -nodecount=20 ./bench mem.prof >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
      
    - name: Upload pprof results
      uses: actions/upload-artifact@v7
      with:
        name: gatewaybench-pprof-results
        path: |
          cpu.prof
          mem.prof