name: CodSpeed

on:
  push:
    branches:
      - "main"
  pull_request:
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  codspeed:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: stable
          cache: true
          cache-dependency-path: 'go.sum'

      - name: Run Go benchmarks
        uses: CodSpeedHQ/action@v4
        with:
          mode: walltime
          run: go test -bench=. -benchtime=5s
